//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ConsoleClient.ServerFirstExercise {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerFirstExercise.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoF", ReplyAction="*")]
        double CtoF(double celsiusTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoF", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CtoFAsync(double celsiusTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoC", ReplyAction="*")]
        double FtoC(double fahrenheitTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FtoCAsync(double fahrenheitTemp);
        
        // CODEGEN: Generating message contract since element name dateShowResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dateShow", ReplyAction="*")]
        ConsoleClient.ServerFirstExercise.dateShowResponse dateShow(ConsoleClient.ServerFirstExercise.dateShowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dateShow", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClient.ServerFirstExercise.dateShowResponse> dateShowAsync(ConsoleClient.ServerFirstExercise.dateShowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/leiToEuro", ReplyAction="*")]
        double leiToEuro(double leiAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/leiToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> leiToEuroAsync(double leiAmount);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dateShowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dateShow", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleClient.ServerFirstExercise.dateShowRequestBody Body;
        
        public dateShowRequest() {
        }
        
        public dateShowRequest(ConsoleClient.ServerFirstExercise.dateShowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class dateShowRequestBody {
        
        public dateShowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dateShowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dateShowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleClient.ServerFirstExercise.dateShowResponseBody Body;
        
        public dateShowResponse() {
        }
        
        public dateShowResponse(ConsoleClient.ServerFirstExercise.dateShowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class dateShowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dateShowResult;
        
        public dateShowResponseBody() {
        }
        
        public dateShowResponseBody(string dateShowResult) {
            this.dateShowResult = dateShowResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleClient.ServerFirstExercise.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleClient.ServerFirstExercise.WebService1Soap>, ConsoleClient.ServerFirstExercise.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CtoF(double celsiusTemp) {
            return base.Channel.CtoF(celsiusTemp);
        }
        
        public System.Threading.Tasks.Task<double> CtoFAsync(double celsiusTemp) {
            return base.Channel.CtoFAsync(celsiusTemp);
        }
        
        public double FtoC(double fahrenheitTemp) {
            return base.Channel.FtoC(fahrenheitTemp);
        }
        
        public System.Threading.Tasks.Task<double> FtoCAsync(double fahrenheitTemp) {
            return base.Channel.FtoCAsync(fahrenheitTemp);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClient.ServerFirstExercise.dateShowResponse ConsoleClient.ServerFirstExercise.WebService1Soap.dateShow(ConsoleClient.ServerFirstExercise.dateShowRequest request) {
            return base.Channel.dateShow(request);
        }
        
        public string dateShow() {
            ConsoleClient.ServerFirstExercise.dateShowRequest inValue = new ConsoleClient.ServerFirstExercise.dateShowRequest();
            inValue.Body = new ConsoleClient.ServerFirstExercise.dateShowRequestBody();
            ConsoleClient.ServerFirstExercise.dateShowResponse retVal = ((ConsoleClient.ServerFirstExercise.WebService1Soap)(this)).dateShow(inValue);
            return retVal.Body.dateShowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClient.ServerFirstExercise.dateShowResponse> ConsoleClient.ServerFirstExercise.WebService1Soap.dateShowAsync(ConsoleClient.ServerFirstExercise.dateShowRequest request) {
            return base.Channel.dateShowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.ServerFirstExercise.dateShowResponse> dateShowAsync() {
            ConsoleClient.ServerFirstExercise.dateShowRequest inValue = new ConsoleClient.ServerFirstExercise.dateShowRequest();
            inValue.Body = new ConsoleClient.ServerFirstExercise.dateShowRequestBody();
            return ((ConsoleClient.ServerFirstExercise.WebService1Soap)(this)).dateShowAsync(inValue);
        }
        
        public double leiToEuro(double leiAmount) {
            return base.Channel.leiToEuro(leiAmount);
        }
        
        public System.Threading.Tasks.Task<double> leiToEuroAsync(double leiAmount) {
            return base.Channel.leiToEuroAsync(leiAmount);
        }

		internal IEnumerable<string> list()
		{
			throw new NotImplementedException();
		}
	}
}
