//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWindowsForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoF", ReplyAction="*")]
        double CtoF(double celsiusTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoF", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CtoFAsync(double celsiusTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoC", ReplyAction="*")]
        double FtoC(double fahrenheitTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FtoCAsync(double fahrenheitTemp);
        
        // CODEGEN: Generating message contract since element name dateShowResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dateShow", ReplyAction="*")]
        ClientWindowsForm.ServiceReference1.dateShowResponse dateShow(ClientWindowsForm.ServiceReference1.dateShowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dateShow", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWindowsForm.ServiceReference1.dateShowResponse> dateShowAsync(ClientWindowsForm.ServiceReference1.dateShowRequest request);
        
        // CODEGEN: Generating message contract since element name itemListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemList", ReplyAction="*")]
        ClientWindowsForm.ServiceReference1.itemListResponse itemList(ClientWindowsForm.ServiceReference1.itemListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemList", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWindowsForm.ServiceReference1.itemListResponse> itemListAsync(ClientWindowsForm.ServiceReference1.itemListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/leiToEuro", ReplyAction="*")]
        double leiToEuro(double leiAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/leiToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> leiToEuroAsync(double leiAmount);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dateShowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dateShow", Namespace="http://tempuri.org/", Order=0)]
        public ClientWindowsForm.ServiceReference1.dateShowRequestBody Body;
        
        public dateShowRequest() {
        }
        
        public dateShowRequest(ClientWindowsForm.ServiceReference1.dateShowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class dateShowRequestBody {
        
        public dateShowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dateShowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dateShowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWindowsForm.ServiceReference1.dateShowResponseBody Body;
        
        public dateShowResponse() {
        }
        
        public dateShowResponse(ClientWindowsForm.ServiceReference1.dateShowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class dateShowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dateShowResult;
        
        public dateShowResponseBody() {
        }
        
        public dateShowResponseBody(string dateShowResult) {
            this.dateShowResult = dateShowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class itemListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="itemList", Namespace="http://tempuri.org/", Order=0)]
        public ClientWindowsForm.ServiceReference1.itemListRequestBody Body;
        
        public itemListRequest() {
        }
        
        public itemListRequest(ClientWindowsForm.ServiceReference1.itemListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class itemListRequestBody {
        
        public itemListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class itemListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="itemListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWindowsForm.ServiceReference1.itemListResponseBody Body;
        
        public itemListResponse() {
        }
        
        public itemListResponse(ClientWindowsForm.ServiceReference1.itemListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class itemListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWindowsForm.ServiceReference1.ArrayOfString itemListResult;
        
        public itemListResponseBody() {
        }
        
        public itemListResponseBody(ClientWindowsForm.ServiceReference1.ArrayOfString itemListResult) {
            this.itemListResult = itemListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientWindowsForm.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientWindowsForm.ServiceReference1.WebService1Soap>, ClientWindowsForm.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CtoF(double celsiusTemp) {
            return base.Channel.CtoF(celsiusTemp);
        }
        
        public System.Threading.Tasks.Task<double> CtoFAsync(double celsiusTemp) {
            return base.Channel.CtoFAsync(celsiusTemp);
        }
        
        public double FtoC(double fahrenheitTemp) {
            return base.Channel.FtoC(fahrenheitTemp);
        }
        
        public System.Threading.Tasks.Task<double> FtoCAsync(double fahrenheitTemp) {
            return base.Channel.FtoCAsync(fahrenheitTemp);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWindowsForm.ServiceReference1.dateShowResponse ClientWindowsForm.ServiceReference1.WebService1Soap.dateShow(ClientWindowsForm.ServiceReference1.dateShowRequest request) {
            return base.Channel.dateShow(request);
        }
        
        public string dateShow() {
            ClientWindowsForm.ServiceReference1.dateShowRequest inValue = new ClientWindowsForm.ServiceReference1.dateShowRequest();
            inValue.Body = new ClientWindowsForm.ServiceReference1.dateShowRequestBody();
            ClientWindowsForm.ServiceReference1.dateShowResponse retVal = ((ClientWindowsForm.ServiceReference1.WebService1Soap)(this)).dateShow(inValue);
            return retVal.Body.dateShowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWindowsForm.ServiceReference1.dateShowResponse> ClientWindowsForm.ServiceReference1.WebService1Soap.dateShowAsync(ClientWindowsForm.ServiceReference1.dateShowRequest request) {
            return base.Channel.dateShowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWindowsForm.ServiceReference1.dateShowResponse> dateShowAsync() {
            ClientWindowsForm.ServiceReference1.dateShowRequest inValue = new ClientWindowsForm.ServiceReference1.dateShowRequest();
            inValue.Body = new ClientWindowsForm.ServiceReference1.dateShowRequestBody();
            return ((ClientWindowsForm.ServiceReference1.WebService1Soap)(this)).dateShowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWindowsForm.ServiceReference1.itemListResponse ClientWindowsForm.ServiceReference1.WebService1Soap.itemList(ClientWindowsForm.ServiceReference1.itemListRequest request) {
            return base.Channel.itemList(request);
        }
        
        public ClientWindowsForm.ServiceReference1.ArrayOfString itemList() {
            ClientWindowsForm.ServiceReference1.itemListRequest inValue = new ClientWindowsForm.ServiceReference1.itemListRequest();
            inValue.Body = new ClientWindowsForm.ServiceReference1.itemListRequestBody();
            ClientWindowsForm.ServiceReference1.itemListResponse retVal = ((ClientWindowsForm.ServiceReference1.WebService1Soap)(this)).itemList(inValue);
            return retVal.Body.itemListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWindowsForm.ServiceReference1.itemListResponse> ClientWindowsForm.ServiceReference1.WebService1Soap.itemListAsync(ClientWindowsForm.ServiceReference1.itemListRequest request) {
            return base.Channel.itemListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWindowsForm.ServiceReference1.itemListResponse> itemListAsync() {
            ClientWindowsForm.ServiceReference1.itemListRequest inValue = new ClientWindowsForm.ServiceReference1.itemListRequest();
            inValue.Body = new ClientWindowsForm.ServiceReference1.itemListRequestBody();
            return ((ClientWindowsForm.ServiceReference1.WebService1Soap)(this)).itemListAsync(inValue);
        }
        
        public double leiToEuro(double leiAmount) {
            return base.Channel.leiToEuro(leiAmount);
        }
        
        public System.Threading.Tasks.Task<double> leiToEuroAsync(double leiAmount) {
            return base.Channel.leiToEuroAsync(leiAmount);
        }
    }
}
